✨ Add a system of menu and roles.
NextCitizens/ncs_discord_bot pull request #14
Opened 2022-05-31 10:04 UTC by martin0024

2022-05-31 16:18 UTC, a9ex requested changes

2022-05-31 16:18 UTC, a9ex commented on index.js
>  client.login(process.env.TOKEN);
`client.login` is better at the end of the file

2022-05-31 16:18 UTC, a9ex commented on index.js
> +const wait = require("util").promisify(setTimeout);
Using `const { setTimeout: sleep } = require('node:timers/promises');` can be better

2022-05-31 16:18 UTC, a9ex commented on slscommands/info/menu.js
> +        } = require("discord.js");
Better outside of `module.exports`

2022-05-31 16:18 UTC, a9ex commented on slscommands/info/menu.js
> +                    },
it would be better if you list the roles in a configuration file I think, especially if it changes a lot

2022-05-31 16:18 UTC, a9ex commented on slscommands/info/menu.js
> +        await interaction.followUp({
You use `followUp` but the interaction has not yet been replied to

2022-05-31 16:18 UTC, a9ex commented on index.js
> +client.on("interactionCreate", async (interaction) => {
In this case, I don't think it's a good solution:

I think that if the command can be invoked by everyone via a slash command, we use `<Message>.awaitComponent` or `createMessageComponentCollector`.

On the other hand, as on some servers, we can do a read-only channel where members choose their roles via the dropdown and in this case it's a good solution

2022-05-31 16:18 UTC, a9ex commented on index.js
> +    } else if (interaction.values[0] === "second_option") {
What if you want to assign more than 2 roles?
The code is not optimized and efficient

2022-05-31 16:18 UTC, a9ex commented on index.js
> +          content: "You have already this role !",
If he already has the role, why not remove the role 🤔

2022-05-31 16:36 UTC, martin-fullstacks commented on index.js
>  client.login(process.env.TOKEN);
This come from the security commit...so it's not me.

2022-05-31 16:37 UTC, martin-fullstacks commented on slscommands/info/menu.js
> +                    },
Look at the config.json...

2022-05-31 16:37 UTC, martin-fullstacks commented on slscommands/info/menu.js
> +        await interaction.followUp({
So need to use `interaction.reply`?

2022-05-31 16:40 UTC, martin-fullstacks commented on index.js
> +    } else if (interaction.values[0] === "second_option") {
In this case you need to add more options in the menu..so he needs to edit the code to do it, it can't handle that.

2022-06-02 18:12 UTC, a9ex requested changes

2022-06-02 18:12 UTC, a9ex commented on index.js
> +
```suggestion
```

2022-06-02 18:12 UTC, a9ex commented on slscommands/info/menu.js
> +        await interaction.followUp({
```suggestion
        await interaction.reply({
```

2022-06-02 18:12 UTC, a9ex commented on slscommands/info/menu.js
> +const wait = require("util").promisify(setTimeout);
```suggestion
```

2022-06-02 18:12 UTC, a9ex commented on slscommands/info/menu.js
> +const { CommandInteraction, Client, Message } = require("discord.js");
```suggestion
const { MessageActionRow, MessageSelectMenu, MessageEmbed} = require("discord.js");
```

2022-06-02 18:12 UTC, a9ex commented on slscommands/info/menu.js
> +        } = require("discord.js");
```suggestion
```

2022-06-02 20:46 UTC, a9ex approved these changes

2022-06-02 20:47 UTC, merged