:wrench: adaptation of paths for the src
NextCitizens/ncs_discord_bot pull request #27
Opened 2022-06-04 09:43 UTC by foltone

2022-06-04 09:44 UTC, foltone commented
without this the bot does not start anymore

2022-06-04 23:22 UTC, a9ex requested changes

2022-06-04 23:22 UTC, a9ex commented on src/events/guildMemberAdd.js
> +const config = require('../../config.exemple.json');
As announced on Discord, config.example.json is a convention for future and current contributors to know the template of the configuration file.
When they work on it and in production, the file should be duplicated and renamed config.json locally, without committing it.

```suggestion
const config = require('../../config.json');
```

2022-06-05 08:23 UTC, foltone commented on src/events/guildMemberAdd.js
> +const config = require('../../config.exemple.json');
ah yes my bad
I fix that

2022-06-05 11:55 UTC, a9ex approved these changes

2022-06-05 11:55 UTC, merged