:memo: Translated from fr to en
NextCitizens/ncs_discord_bot pull request #7
Opened 2022-05-29 21:32 UTC by martin-fullstacks

2022-05-29 21:38 UTC, a9ex approved these changes

2022-05-30 16:21 UTC, a9ex requested changes
I hadn't seen this but I think it's better to do 2 separate PRs for translation & adding new commands (kick & unkick)

2022-05-30 18:00 UTC, martin-fullstacks commented on commands/aide/help.js
> +                            `User \`${prefix}help\` to have more informations about the command. \n For example: \`${prefix}help ping\`.\n\n`
Oh yes my bad !

2022-05-30 18:01 UTC, martin-fullstacks commented
Ok i will close this rp and after how can i do an another rp with the last commit that i have made ?

2022-05-30 18:18 UTC, a9ex approved these changes

2022-05-30 18:23 UTC, merged